-- Seed movies
INSERT INTO movies (slug, telugu_title, telugu_poster_url, telugu_synopsis, source_title, source_poster_url, source_synopsis, category)
VALUES 
('gabbarsingh-dabangg', 'Gabbarsingh', 'https://m.media-amazon.com/images/M/MV5BNGEyMGFkYzMtMGNkMi00YTAyLWFhYTQtZTUzYTAxMGM4MzQyXkEyXkFqcGc@._V1_.jpg', 'A brave cop takes on a local goon in a village where lawlessness prevails.', 'Dabangg', 'https://m.media-amazon.com/images/M/MV5BMTM0NzY3MTcyMF5BMl5BanBnXkFtZTcwNzY3Njk3Mw@@._V1_.jpg', 'A corrupt police officer faces challenges from his family, gangsters and politicians.', 'Remake'),
('dhruva-thanioruvan', 'Dhruva', 'https://m.media-amazon.com/images/M/MV5BMjA5OTg5Mzg1MV5BMl5BanBnXkFtZTgwNjA2NjI4MDI@._V1_.jpg', 'A committed police officer is on a mission to destroy the most corrupt person in the country.', 'Thani Oruvan', 'https://m.media-amazon.com/images/M/MV5BMTUwOTY3Nzc0MV5BMl5BanBnXkFtZTgwNjA2NjI4MDI@._V1_.jpg', 'A small-time thief becomes a powerful man and a police officer decides to bring him down.', 'Remake'),
('khaidi150-kathi', 'Khaidi No. 150', 'https://m.media-amazon.com/images/M/MV5BMTUwOTY3Nzc0MV5BMl5BanBnXkFtZTgwNjA2NjI4MDI@._V1_.jpg', 'A man escapes from prison and takes the place of his doppelganger to fight for farmers.', 'Kaththi', 'https://m.media-amazon.com/images/M/MV5BMTUwOTY3Nzc0MV5BMl5BanBnXkFtZTgwNjA2NjI4MDI@._V1_.jpg', 'A man escapes from prison and takes the place of his doppelganger to fight for farmers.', 'Remake'),
('billa-billa', 'Billa', 'https://m.media-amazon.com/images/M/MV5BMTUwOTY3Nzc0MV5BMl5BanBnXkFtZTgwNjA2NjI4MDI@._V1_.jpg', 'A gangster is killed and his lookalike is sent by a cop to infiltrate the gang.', 'Billa', 'https://m.media-amazon.com/images/M/MV5BMTUwOTY3Nzc0MV5BMl5BanBnXkFtZTgwNjA2NjI4MDI@._V1_.jpg', 'A gangster is killed and his lookalike is sent by a cop to infiltrate the gang.', 'Remake'),
('shankar-dada-mbbs-munna-bhai', 'Shankar Dada M.B.B.S.', 'https://m.media-amazon.com/images/M/MV5BMTUwOTY3Nzc0MV5BMl5BanBnXkFtZTgwNjA2NjI4MDI@._V1_.jpg', 'A local thug decides to become a doctor to fulfill his father''s dream.', 'Munna Bhai M.B.B.S.', 'https://m.media-amazon.com/images/M/MV5BMTUwOTY3Nzc0MV5BMl5BanBnXkFtZTgwNjA2NjI4MDI@._V1_.jpg', 'A local thug decides to become a doctor to fulfill his father''s dream.', 'Remake')
ON CONFLICT (slug) DO NOTHING;
